name: cdc_pharmacy_project
version: "1.0.0"
config-version: 2

profile: cdc_pharmacy_project

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  cdc_pharmacy_project:
    +materialized: view
    staging:
      +materialized: table